# Generated by Django 5.1.6 on 2025-03-17 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_directchat_alter_message_room_delete_chatroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directchat',
            unique_together={('user1', 'user2')},
        ),
    ]
