# Generated by Django 5.1.6 on 2025-03-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_aboutparameter_category_services_blog_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='logo',
            field=models.CharField(max_length=255),
        ),
    ]
