# Generated by Django 5.1.6 on 2025-03-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
