# Generated by Django 5.1.6 on 2025-04-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_historicalfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_forgotpassword',
            field=models.BooleanField(default=False),
        ),
    ]
