# Generated by Django 5.2.3 on 2025-06-26 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_user_is_forgotpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gst_number',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}[A-Z]{1}[0-9A-Z]{1}$', 'Enter a valid GST number.')]),
        ),
    ]
